services:
  app-operacoes:
    container_name: "operacoes"
    build:
      context: .
      dockerfile: Dockerfile
      target: development-operacoes
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 7002
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@db-operacoes:5432/lanchonete?schema=public
      MICROSERVICO_CADASTROS_URL: http://app-cadastros:7001
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      PEDIDO_QUEUE_URL: http://localstack:4566/000000000000/pedido-queue
      PAGAMENTO_QUEUE_URL: http://localstack:4566/000000000000/pagamento-queue
    ports:
      - 7002:7002
    command: sh -c "npx prisma migrate deploy && npm run dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db-operacoes
      - localstack
  
  localstack:
    image: localstack/localstack:latest
    expose:
      - 4566
    ports:
      - 4566:4566
    environment:
      SERVICES: sqs
    volumes:
      - ./tooling/sqs:/etc/localstack/init/ready.d/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-operacoes:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-operacoes"
    ports:
      - "8082:8082"
    volumes:
      - ./tooling/swagger/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
    default:
        name: lanchonete-network
